server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: url-github
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t

